[package]
name = "snake-wasm"
version = "0.1.0"
authors = ["Yiran Sheng <shengyiran@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]

js-sys = "0.3.2"
web-sys = "0.3.2"
wasm-bindgen = "0.2.25"
